source=~/.config/hypr/hyprlock.conf

auth {
    pam {
        enabled = true
        module = pam-my-fprint-pass-hyprlock
    }

    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning fingerprint
        retry_delay = 250
    }
}
