$lock_cmd = qs -c ii ipc call lock activate
$suspend_cmd = systemctl suspend || loginctl suspend
$on_battery_cmd = sh -c 'for p in /sys/class/power_supply/*; do [ -f "$p/type" ] || continue; [ "$(cat "$p/type")" = "Mains" ] || continue; [ -f "$p/online" ] || continue; [ "$(cat "$p/online")" = "1" ] && exit 1; done; exit 0'

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = $lock_cmd
    after_sleep_cmd = qs -c ii ipc call lock focus
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = $lock_cmd
}

listener {
    timeout = 1800 # 30mins
    on-timeout = $on_battery_cmd && hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 7200 # 2hrs
    on-timeout = $on_battery_cmd && $suspend_cmd
}
